import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("games_data.csv", sep="\t")
plt.clf()
plt.xlabel("Number of records")
plt.ylabel("Running Time (ns)")
plt.title("Running Time vs Number of Records - Search - Games")
plt.plot(df["n"], df["search_time"])
plt.savefig("graph/games_running_time_search.png")
plt.clf()
plt.xlabel("Number of records")
plt.ylabel("Running Time (s)")
plt.title("Running Time vs Number of Records - Insert - Games")
plt.plot(df["n"], df["insert_time"]/1000000000)
plt.savefig("graph/games_running_time_insert.png")
plt.clf()
plt.xlabel("Number of records")
plt.ylabel("Secondary Memory Accesses")
plt.title("Secondary Memory Accesses vs Number of Records - Search - Games")
plt.plot(df["n"], df["search_memory"])
plt.savefig("graph/games_secondary_memory_search.png")
plt.clf()
plt.xlabel("Number of records")
plt.ylabel("Secondary Memory Accesses")
plt.title("Secondary Memory Accesses vs Number of Records - Insert - Games")
plt.plot(df["n"], df["insert_memory"])
plt.savefig("graph/games_secondary_memory_insert.png")

df = pd.read_csv("movies_data.csv", sep="\t")
plt.clf()
plt.xlabel("Number of records")
plt.ylabel("Running Time (ns)")
plt.title("Running Time vs Number of Records - Search - Movies")
plt.plot(df["n"], df["search_time"])
plt.savefig("graph/movies_running_time_search.png")
plt.clf()
plt.xlabel("Number of records")
plt.ylabel("Running Time (ms)")
plt.title("Running Time vs Number of Records - Insert - Movies")
plt.plot(df["n"], df["insert_time"]/1000000 )
plt.savefig("graph/movies_running_time_insert.png")
plt.clf()
plt.xlabel("Number of records")
plt.ylabel("Secondary Memory Accesses")
plt.title("Secondary Memory Accesses vs Number of Records - Search - Movies")
plt.plot(df["n"], df["search_memory"])
plt.savefig("graph/movies_secondary_memory_search.png")
plt.clf()
plt.xlabel("Number of records")
plt.ylabel("Secondary Memory Accesses")
plt.title("Secondary Memory Accesses vs Number of Records - Insert - Movies")
plt.plot(df["n"], df["insert_memory"])
plt.savefig("graph/movies_secondary_memory_insert.png")
plt.clf()

